---
- hosts: web
  remote_user: ubuntu
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx and PHP-FPM
      apt:
        name:
          - nginx
          - php-fpm
        state: present

    - name: Copy Nginx configuration file
      copy:
        src: 4_nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy PHP-FPM configuration file
      copy:
        src: 5_php-fpm.conf
        dest: /etc/php/7.4/fpm/php-fpm.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy sample web application files
      copy:
        src: 6_web.py
        dest: /usr/share/nginx/html/
        owner: www-data
        group: www-data
        mode: '0755'
  
    - name: Configure Nginx to serve Flask application
      copy:
        src: 3_flask-app.conf
        dest: /etc/nginx/sites-available/flask
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Enable Flask site in Nginx
      file:
        src: /etc/nginx/sites-available/flask
        dest: /etc/nginx/sites-enabled/flask
        state: link
      notify: restart nginx


    - name: Start Nginx service
      systemd:
        name: nginx
        state: started

    - name: Start PHP-FPM service
      systemd:
        name: php7.4-fpm
        state: started

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
